import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const RAIZ = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = resolve(RAIZ, 'dist');
const datos = JSON.parse(readFileSync(resolve(RAIZ, 'src/data/estados.json'),'utf8'));
const site = JSON.parse(readFileSync(resolve(RAIZ, 'src/data/paginas.json'),'utf8'));
const origen = site.sitio.origen;
const plantilla = readFileSync(resolve(DIST,'index.html'),'utf8');
const esc = (v) => String(v ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const dinero = (n) => new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
const numero = (n) => new Intl.NumberFormat('es-MX').format(n);

function meta(html, clave, valor, propiedad=false){const attr=propiedad?'property':'name';const re=new RegExp(`<meta\\s+${attr}=["']${clave}["'][^>]*>`,'i');const tag=`<meta ${attr}="${clave}" content="${esc(valor)}" />`;return re.test(html)?html.replace(re,tag):html.replace('</head>',`    ${tag}\n  </head>`)}
function base({titulo,descripcion,url,breadcrumbs,tipo='WebPage'}){let html=plantilla.replace(/<script type="application\/ld\+json">[\s\S]*?<\/script>\s*/gi,'');html=html.replace(/<title>[\s\S]*?<\/title>/i,`<title>${esc(titulo)}</title>`);html=meta(html,'description',descripcion);html=meta(html,'og:title',titulo,true);html=meta(html,'og:description',descripcion,true);html=meta(html,'og:url',url,true);html=meta(html,'og:type','website',true);html=meta(html,'twitter:title',titulo);html=meta(html,'twitter:description',descripcion);const canonical=`<link rel="canonical" href="${url}" />`;html=/<link\s+rel=["']canonical["'][^>]*>/i.test(html)?html.replace(/<link\s+rel=["']canonical["'][^>]*>/i,canonical):html.replace('</head>',`    ${canonical}\n  </head>`);const schema={'@context':'https://schema.org','@graph':[{'@type':tipo,name:titulo.split('|')[0].trim(),url,description:descripcion,inLanguage:'es-MX',publisher:{'@type':'Organization',name:'MiLana',url:origen}},{'@type':'BreadcrumbList',itemListElement:breadcrumbs.map((b,i)=>({'@type':'ListItem',position:i+1,name:b.nombre,item:b.url}))}]};return html.replace('</head>',`    <script type="application/ld+json">${JSON.stringify(schema)}</script>\n  </head>`)}

const ordenIngreso=[...datos.estados].sort((a,b)=>b.ingreso-a.ingreso);
const ordenOcupados=[...datos.estados].sort((a,b)=>b.ocupados-a.ocupados);
const listaEstados=datos.estados.map((e)=>`<li><a href="/estados/${e.slug}">${esc(e.estado)}</a> — ${dinero(e.ingreso)} mensuales · ${numero(e.ocupados)} profesionistas ocupados</li>`).join('');

function construirHub(){const ruta='/estados';const url=`${origen}${ruta}`;const titulo='Trabajo y salarios por estado en México 2026 | MiLana';const descripcion='Elige cualquiera de los 32 estados de México y consulta ingreso profesional promedio, profesionistas ocupados y comparación nacional con ENOE 2026-T2.';let html=base({titulo,descripcion,url,tipo:'CollectionPage',breadcrumbs:[{nombre:'Inicio',url:`${origen}/`},{nombre:'Estados',url}]});const cuerpo=`<div id="root"><main data-static-seo="estados"><nav><a href="/">Inicio</a> / Estados</nav><h1>Trabajo y salarios por estado en México 2026</h1><p>MiLana usa el mismo corte oficial para las 32 entidades: ${esc(datos.fuente.nombre)}, ${esc(datos.fuente.periodo)}.</p><p>El promedio profesional nacional del corte es ${dinero(datos.promedioNacional)} mensuales. El ingreso estatal no equivale a costo de vida, sueldo inicial ni vacantes abiertas.</p><h2>Elige tu estado</h2><ul>${listaEstados}</ul><p><strong>Fuente:</strong> ${esc(datos.fuente.instituciones)}. ${esc(datos.nota)}</p></main></div>`;html=html.replace(/<div id="root">[\s\S]*?<\/div>/i,cuerpo);const destino=resolve(DIST,'estados','index.html');mkdirSync(dirname(destino),{recursive:true});writeFileSync(destino,html,'utf8')}

function construirEstado(e){const ruta=`/estados/${e.slug}`;const url=`${origen}${ruta}`;const titulo=`Trabajo y salarios en ${e.estado} 2026 | MiLana`;const descripcion=`${e.estado}: ${dinero(e.ingreso)} de ingreso profesional promedio mensual y ${numero(e.ocupados)} profesionistas ocupados, con ENOE 2026-T2.`;const rankIngreso=ordenIngreso.findIndex((x)=>x.slug===e.slug)+1;const rankOcupados=ordenOcupados.findIndex((x)=>x.slug===e.slug)+1;const diferencia=e.ingreso-datos.promedioNacional;const pct=diferencia/datos.promedioNacional*100;let html=base({titulo,descripcion,url,breadcrumbs:[{nombre:'Inicio',url:`${origen}/`},{nombre:'Estados',url:`${origen}/estados`},{nombre:e.estado,url}]});const cuerpo=`<div id="root"><main data-static-seo="estado"><nav><a href="/">Inicio</a> / <a href="/estados">Estados</a> / ${esc(e.estado)}</nav><h1>Trabajo, salarios y decisiones de dinero en ${esc(e.estado)}</h1><p>El Observatorio Laboral reporta un ingreso profesional promedio mensual de <strong>${dinero(e.ingreso)}</strong> y <strong>${numero(e.ocupados)}</strong> profesionistas ocupados en ${esc(e.estado)} al segundo trimestre de 2026.</p><h2>Cómo se compara con México</h2><ul><li><strong>Promedio profesional estatal:</strong> ${dinero(e.ingreso)}</li><li><strong>Promedio profesional nacional:</strong> ${dinero(datos.promedioNacional)}</li><li><strong>Diferencia:</strong> ${diferencia>=0?'+':''}${pct.toFixed(1)}%</li><li><strong>Posición por ingreso promedio:</strong> ${rankIngreso} de 32</li><li><strong>Posición por profesionistas ocupados:</strong> ${rankOcupados} de 32</li></ul><h2>Qué no significa este promedio</h2><p>No representa el sueldo de cada carrera dentro de ${esc(e.estado)}, no mide costo de vida y no equivale a vacantes. MiLana no publica cruces estatales que la fuente no entregue.</p><h2>Continúa con tus números</h2><ul><li><a href="/carreras">Explorar carreras y profesiones</a></li><li><a href="/carreras/comparar">Comparar dos carreras</a></li><li><a href="/calculadoras/bruto-a-neto">Calcular sueldo neto</a></li><li><a href="/finanzas/mi-situacion">Analizar mi situación</a></li></ul><p><strong>Fuente:</strong> ${esc(datos.fuente.nombre)}. ${esc(datos.fuente.periodo)}. ${esc(datos.nota)}</p></main></div>`;html=html.replace(/<div id="root">[\s\S]*?<\/div>/i,cuerpo);const destino=resolve(DIST,'estados',e.slug,'index.html');mkdirSync(dirname(destino),{recursive:true});writeFileSync(destino,html,'utf8')}

construirHub();
datos.estados.forEach(construirEstado);
console.log(`estados: 1 hub + ${datos.estados.length} páginas estatales generadas`);
